import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import QuoteList from '../components/QuoteList'

import { Quote } from '../types/Quote'
import api from '../libs/api'
import Btn from '../components/Btn'

type Props = {
  quotes: Quote[];
}

const Home = ({ quotes }: Props) => {
  return (
    <div>
      
      <Head>
        <title>Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex justify-center">
        <div className="flex justify-start w-5/6">
          <Btn text='Add' link='/add'/>
        </div>
      </div>

      <QuoteList quotes={quotes} />

      <Footer />

    </div>
  )
}

export const getServerSideProps = async () => {
  const quotes = await api.getAllQuote();

  return {
      props: {
          quotes
      }
  }
}

export default Home
